- job:
    name: ospurge-functional
    parent: devstack-tox-functional-consumer
    timeout: 3600
    required-projects:
      # Additional supported projects
      - openstack/designate
      - openstack/octavia
    roles:
      - zuul: openstack-infra/devstack
    vars:
        devstack_plugins:
            designate: https://opendev.org/openstack/designate
            octavia: https://opendev.org/openstack/octavia
        devstack_localrc:
            DISABLE_AMP_IMAGE_BUILD: True
        devstack_local_conf:
            post-config:
                $OCTAVIA_CONF:
                    controller_worker:
                        amphora_driver: amphora_noop_driver
                        compute_driver: compute_noop_driver
                        network_driver: network_noop_driver
                    certificates:
                        cert_manager: local_cert_manager
        devstack_services:
            octavia: true
            o-api: true
            o-cw: true
            o-hm: false
            o-hk: false
        tox_envlist: functional
    irrelevant-files: &dsvm-irrelevant-files
      - ^(test-|)requirements.txt$
      - ^.*\.rst$
      - ^.git.*$
      - ^\.testr.conf$
      - ^LICENSE$
      - ^doc/.*$
      - ^releasenotes/.*$
      - ^setup.cfg$
      - ^tox.ini$

- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-cover-jobs
      - build-openstack-docs-pti
    check:
      jobs:
        - ospurge-functional
    gate:
      jobs:
        - ospurge-functional
